disableSerialization;
params ["_display"];

private _nodes = _display getVariable ["DB_UIEditor_Nodes", []];
private _gridControl = _display getVariable ["DB_UIEditor_Grid", controlNull];
private _grid = lbCurSel _gridControl;
private _export = _display getVariable ["DB_UIEditor_Export", controlNull];
private _lines = ["// Generated by DB UI Editor"];
private _quote = toString [34];

if (_grid == 3) then {
    _lines pushBack format ["#include %1\a3\ui_f\hpp\definecommongrids.inc%1", _quote];
};

private _baseClasses = [];
{
    _baseClasses pushBackUnique (_x # 3);
} forEach _nodes;

{
    _lines pushBack format ["class %1;", _x];
} forEach _baseClasses;

if (_baseClasses isNotEqualTo []) then {
    _lines pushBack "";
};

_lines append [
    "class DB_ExportedDisplay",
    "{",
    "    idd = -1;",
    "    movingEnable = 0;",
    "",
    "    class Controls",
    "    {"
];

private _makeIndent = {
    params ["_count"];
    private _indent = "";
    for "_index" from 1 to _count do {
        _indent = _indent + "    ";
    };
    _indent
};

private _positionLines = {
    params ["_position", "_nested"];
    _position params ["_x", "_y", "_w", "_h"];

    switch (_grid) do {
        case 0: {
            if (_nested) then {
                [
                    format ["x = %1 * safeZoneW;", _x toFixed 4],
                    format ["y = %1 * safeZoneH;", _y toFixed 4],
                    format ["w = %1 * safeZoneW;", _w toFixed 4],
                    format ["h = %1 * safeZoneH;", _h toFixed 4]
                ]
            } else {
                [
                    format ["x = safeZoneX + %1 * safeZoneW;", _x toFixed 4],
                    format ["y = safeZoneY + %1 * safeZoneH;", _y toFixed 4],
                    format ["w = %1 * safeZoneW;", _w toFixed 4],
                    format ["h = %1 * safeZoneH;", _h toFixed 4]
                ]
            }
        };
        case 1: {
            if (_nested) then {
                [
                    format ["x = %1 * pixelW * pixelGrid;", _x toFixed 2],
                    format ["y = %1 * pixelH * pixelGrid;", _y toFixed 2],
                    format ["w = %1 * pixelW * pixelGrid;", _w toFixed 2],
                    format ["h = %1 * pixelH * pixelGrid;", _h toFixed 2]
                ]
            } else {
                [
                    format ["x = safeZoneX + %1 * pixelW * pixelGrid;", _x toFixed 2],
                    format ["y = safeZoneY + %1 * pixelH * pixelGrid;", _y toFixed 2],
                    format ["w = %1 * pixelW * pixelGrid;", _w toFixed 2],
                    format ["h = %1 * pixelH * pixelGrid;", _h toFixed 2]
                ]
            }
        };
        case 2: {
            [
                format ["x = %1 * pixelW * pixelGrid;", _x toFixed 2],
                format ["y = %1 * pixelH * pixelGrid;", _y toFixed 2],
                format ["w = %1 * pixelW * pixelGrid;", _w toFixed 2],
                format ["h = %1 * pixelH * pixelGrid;", _h toFixed 2]
            ]
        };
        case 3: {
            if (_nested) then {
                [
                    format ["x = %1 * GUI_GRID_W;", _x toFixed 3],
                    format ["y = %1 * GUI_GRID_H;", _y toFixed 3],
                    format ["w = %1 * GUI_GRID_W;", _w toFixed 3],
                    format ["h = %1 * GUI_GRID_H;", _h toFixed 3]
                ]
            } else {
                [
                    format ["x = GUI_GRID_X + %1 * GUI_GRID_W;", _x toFixed 3],
                    format ["y = GUI_GRID_Y + %1 * GUI_GRID_H;", _y toFixed 3],
                    format ["w = %1 * GUI_GRID_W;", _w toFixed 3],
                    format ["h = %1 * GUI_GRID_H;", _h toFixed 3]
                ]
            }
        };
        default {
            [
                format ["x = %1;", _x toFixed 6],
                format ["y = %1;", _y toFixed 6],
                format ["w = %1;", _w toFixed 6],
                format ["h = %1;", _h toFixed 6]
            ]
        };
    }
};

private _writeChildren = {};
_writeChildren = {
    params ["_parentId", "_depth"];

    {
        _x params ["_id", "_control", "_nodeParentId", "_class", "", "_isGroup"];

        if (_nodeParentId == _parentId) then {
            private _indent = [_depth] call _makeIndent;
            private _propertyIndent = [_depth + 1] call _makeIndent;
            private _position = if (_class == "RscMapControl") then {
                ctrlMapPosition _control
            } else {
                ctrlPosition _control
            };

            if (_nodeParentId < 0) then {
                private _canvasPosition = ctrlPosition (_display getVariable ["DB_UIEditor_CanvasControl", controlNull]);
                _position set [0, (_position # 0) + (_canvasPosition # 0)];
                _position set [1, (_position # 1) + (_canvasPosition # 1)];
            };

            private _gridPosition = [_position, _grid, _nodeParentId >= 0] call DB_fnc_uiEditorPosition;

            _lines pushBack format ["%1class Control_%2: %3", _indent, _id, _class];
            _lines pushBack format ["%1{", _indent];

            {
                _lines pushBack (_propertyIndent + _x);
            } forEach ([_gridPosition, _nodeParentId >= 0] call _positionLines);

            if (!_isGroup) then {
                private _text = [ctrlText _control, _quote, _quote + _quote] call BIS_fnc_replaceString;
                if (_text != "") then {
                    _lines pushBack format ["%1text = %2%3%2;", _propertyIndent, _quote, _text];
                };
            };

            if (_isGroup) then {
                _lines pushBack "";
                _lines pushBack format ["%1class Controls", _propertyIndent];
                _lines pushBack format ["%1{", _propertyIndent];
                [_id, _depth + 2] call _writeChildren;
                _lines pushBack format ["%1};", _propertyIndent];
            };

            _lines pushBack format ["%1};", _indent];
        };
    } forEach _nodes;
};

[-1, 2] call _writeChildren;

_lines append [
    "    };",
    "};"
];

_export ctrlSetText (_lines joinString endl);
